In [1]:
#### 1. Import the numpy package under the name `np` (★☆☆)
import numpy as np

In [13]:
#### 2. Create a null vector of size 10 (★☆☆)
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
null_vector = np.zeros(10)
null_vector[4]=1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [18]:
#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
np.arange(10,50,1)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [27]:
#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
matrix3 = np.arange(0,9).reshape(3,3)
matrix3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
a = np.array([1,2,0,0,4,0])
np.nonzero(a)

In [24]:
#### 7. Create a 3x3 identity matrix (★☆☆)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
#### 8. Create a 3x3x3 array with random values (★☆☆)
np.random.seed(123)
a = np.random.random((3,3,3))
a

array([[[0.69646919, 0.28613933, 0.22685145],
        [0.55131477, 0.71946897, 0.42310646],
        [0.9807642 , 0.68482974, 0.4809319 ]],

       [[0.39211752, 0.34317802, 0.72904971],
        [0.43857224, 0.0596779 , 0.39804426],
        [0.73799541, 0.18249173, 0.17545176]],

       [[0.53155137, 0.53182759, 0.63440096],
        [0.84943179, 0.72445532, 0.61102351],
        [0.72244338, 0.32295891, 0.36178866]]])

In [40]:
#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
np.random.seed(123)
np.min(p), np.max(p)

(0.01612920669501683, 0.9953584820340174)

In [42]:
#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
np.mean(np.random.random(30))

0.5123262763376384

In [59]:
#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [45]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [53]:
np.diag(np.arange(4))

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3]])

In [54]:
np.diag(1 + np.arange(4))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [58]:
np.diag(1 + np.arange(4), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [ ]:
#### 12. Normalize a 5x5 random matrix (★☆☆)
#hint: (x -mean)/std`

In [103]:
c = np.random.random((5,5))
c

array([[0.70938569, 0.92455188, 0.46733027, 0.37510915, 0.54286042],
       [0.85891684, 0.65215387, 0.2329799 , 0.7745802 , 0.1346135 ],
       [0.16555997, 0.61268228, 0.23878341, 0.70477855, 0.34951853],
       [0.27742396, 0.99891841, 0.04061612, 0.64582252, 0.03869959],
       [0.76021026, 0.23008996, 0.08983187, 0.64844971, 0.73260122]])

In [99]:
c_max, c_min = c.max(), c.min()
c_max, c_min

(0.9538184033144764, 0.013159831290861401)

In [102]:
c = (c - c_min)/c_max - c_min
c

array([[ 0.25766743,  0.3909834 ,  0.16688094,  0.97304317,  0.08090425],
       [ 0.6285228 ,  0.43612648,  0.41706695,  0.3630459 ,  0.88339959],
       [ 0.26710017, -0.00538442,  0.93559224,  0.87937951,  0.26335188],
       [ 0.52187673,  0.08741316,  0.07099375,  0.85105738,  0.40317297],
       [ 0.66679844,  0.96191123,  0.2300424 , -0.01315983, -0.00163922]])

In [ ]:
#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

In [107]:
lst_lst1 = [[1,2,3],[4,5,6],[7,8,9]]
lst_lst2 = [[1,2,0],[4,5,0],[7,8,0]]
e = np.array(lst_lst1)
f = np.array(lst_lst2)
np.intersect1d(e,f)

array([1, 2, 4, 5, 7, 8])

In [63]:
#### 14. Create a random vector of size 10 and sort it (★★☆)
np.sort(np.random.random(10))

array([0.04359146, 0.30476807, 0.31876643, 0.35739757, 0.38895057,
       0.39818568, 0.55438325, 0.6919703 , 0.84167   , 0.92513249])

In [108]:
#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
v10 = (np.random.random(10))
v10[v10.argmax()] = 0
v10

array([0.52694064, 0.        , 0.52071832, 0.03503317, 0.14360097,
       0.79560459, 0.49197605, 0.44187927, 0.31843478, 0.2845492 ])

In [ ]:
#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

In [111]:
f

array([[1, 2, 0],
       [4, 5, 0],
       [7, 8, 0]])

In [110]:
np.mean(f)  #global mean

3.0

In [112]:
np.mean(f, axis=1)   #mean of each row

array([1., 3., 5.])

In [113]:
np.mean(f, axis=0) #mean of each column

array([4., 5., 0.])

In [ ]:
#### 17. How to get the n largest values of an array (★★★)
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5


In [115]:
Z

array([8513, 1482, 5199, ..., 5106, 5907, 4945])

In [119]:
Z[np.argsort(Z)[-5]]

9995

In [ ]:
#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`

In [125]:
mm = np.random.random((5,3))
mm

array([[0.03428777, 0.03857196, 0.60442027],
       [0.92750308, 0.00770863, 0.7291941 ],
       [0.36807425, 0.43517258, 0.37517993],
       [0.6218162 , 0.12527499, 0.11563778],
       [0.33641535, 0.09264896, 0.87315779]])

In [128]:
np.where(mm > 0.1)

(array([0, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4]),
 array([2, 0, 2, 0, 1, 2, 0, 1, 2, 0, 2]))