In [1]:
#### 1. Import the numpy package under the name `np` (★☆☆)
import numpy as np

In [13]:
#### 2. Create a null vector of size 10 (★☆☆)
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
null_vector = np.zeros(10)
null_vector[4]=1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [18]:
#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
np.arange(10,50,1)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

In [ ]:
#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
a = np.array([1,2,0,0,4,0])
np.nonzero(a)

In [24]:
#### 7. Create a 3x3 identity matrix (★☆☆)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

In [ ]:
#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

In [ ]:
#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

In [ ]:
#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

In [ ]:
#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

In [ ]:
#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

In [ ]:
#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

In [ ]:
#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

In [ ]:
#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

In [ ]:
#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`

In [ ]:
#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`